#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export EDGE_LOAD_SOAK_DURATION_SECONDS="${EDGE_LOAD_SOAK_DURATION_SECONDS:-1800}"
export EDGE_LOAD_CONCURRENCY="${EDGE_LOAD_CONCURRENCY:-1}"
export EDGE_LOAD_SOAK_REQUEST_INTERVAL_MS="${EDGE_LOAD_SOAK_REQUEST_INTERVAL_MS:-1500}"
export EDGE_LOAD_WARMUP_REQUESTS="${EDGE_LOAD_WARMUP_REQUESTS:-20}"
export EDGE_LOAD_FOOD_P95_MS="${EDGE_LOAD_FOOD_P95_MS:-1500}"
export EDGE_LOAD_SETTINGS_P95_MS="${EDGE_LOAD_SETTINGS_P95_MS:-1000}"
export EDGE_LOAD_MAX_ERROR_RATE="${EDGE_LOAD_MAX_ERROR_RATE:-0.01}"
export EDGE_LOAD_REPORT_PATH="${EDGE_LOAD_REPORT_PATH:-supabase/tests_edge_soak_report.json}"

echo "Running Supabase edge soak profile:"
echo "  EDGE_LOAD_SOAK_DURATION_SECONDS=${EDGE_LOAD_SOAK_DURATION_SECONDS}"
echo "  EDGE_LOAD_CONCURRENCY=${EDGE_LOAD_CONCURRENCY}"
echo "  EDGE_LOAD_SOAK_REQUEST_INTERVAL_MS=${EDGE_LOAD_SOAK_REQUEST_INTERVAL_MS}"
echo "  EDGE_LOAD_REPORT_PATH=${EDGE_LOAD_REPORT_PATH}"

bash scripts/run_supabase_edge_load.sh
